const fs=require('fs'),vm=require('vm'),assert=require('assert');
const dir=__dirname;
const read=n=>fs.readFileSync(dir+'/'+n,'utf8');
for(const name of ['Dashboard','DataModel'])new vm.Script(read(name+'.html').replace(/^<script>\s*/,'').replace(/\s*<\/script>$/,''));
const ctx=vm.createContext({console, Date, Utilities:{formatDate:()=> '2026-10-05T00:00:00+07:00'}});
vm.runInContext(read('Config.gs')+'\n'+read('Code.gs'),ctx);
const evaluate=s=>vm.runInContext(s,ctx);
assert.equal(evaluate("normalize_('Affected_Households','1,234')"),1234);
assert.equal(evaluate("normalize_('capacity','')"),null);
assert.equal(evaluate("normalize_('Report_Date','05/10/2569')"),'2026-10-05T00:00:00+07:00');
assert.equal(evaluate("transform_('BKK_water_DB',[{district_or_area:'เขตบางรัก'}])[0].province"),'กรุงเทพมหานคร');
evaluate(`SpreadsheetApp={openById:()=>({getSheetByName:name=>({getDataRange:()=>({getValues:()=>[CONFIG.required[name]]})})})}`);
let data=evaluate('getDashboardData()');
assert.equal(Object.keys(data.sourceStatus).length,5);
assert(Object.values(data.sourceStatus).every(s=>s.status==='ok'));
evaluate(`SpreadsheetApp={openById:()=>({getSheetByName:name=>name==='shelter_DB'?null:({getDataRange:()=>({getValues:()=>[CONFIG.required[name]]})})})}`);
data=evaluate('getDashboardData()');
assert.equal(data.sourceStatus.shelter_DB.status,'error');
assert.equal(data.sourceStatus.Disaster_DB.status,'ok');
data=evaluate("getDashboardData('thai_water_DB')");assert.equal(Object.keys(data.sourceStatus).length,1);
assert.throws(()=>evaluate("getDashboardData('invalid')"));
assert(!read('Dashboard.html').includes("fetch('/"));
assert(!read('Index.html').includes('src="/'));
JSON.stringify(data);
console.log('PASS: syntax, normalization, mapping, partial failure, retry, bundled paths');
